project_id = "hqfaqofkvmmdjlrhwkgt"

[functions.generate-portal-token]
verify_jwt = false

[functions.validate-portal-token]
verify_jwt = false

[functions.client-respond]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = false
